spring:
  application:
    name: hotel-management
  profiles:
    active: dev
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080
